# -*- coding: utf-8 -*-
"""FDSA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bFQ3niTcd1JexbZhTCy4jITM4Qjtmaey
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

births = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Birthrate-Analysis/master/births.csv")
print(births.head())

births['decade'] = 10 * (births['year'] // 10)

births.pivot_table('births', index='decade', columns='gender', aggfunc='sum')
print(births.head())

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

birth_decade = births.pivot_table('births', index='decade', columns='gender', aggfunc='sum')

birth_decade.plot()
plt.ylabel("Total births per year")
plt.show()